let stylesName = [ 
 "animation-delay"
, "animation-direction"
, "animation-duration"
, "animation-fill-mode"
, "animation-iteration-count"
, "animation-name"
, "animation-play-state"
, "animation-timing-function"
, "background-attachment"
, "background-blend-mode"
, "background-clip"
, "background-color"
, "background-image"
, "background-origin"
, "background-position"
, "background-repeat"
, "background-size"
, "border-bottom-color"
, "border-bottom-left-radius"
, "border-bottom-right-radius"
, "border-bottom-style"
, "border-bottom-width"
, "border-collapse"
, "border-image-outset"
, "border-image-repeat"
, "border-image-slice"
, "border-image-source"
, "border-image-width"
, "border-left-color"
, "border-left-style"
, "border-left-width"
, "border-right-color"
, "border-right-style"
, "border-right-width"
, "border-top-color"
, "border-top-left-radius"
, "border-top-right-radius"
, "border-top-style"
, "border-top-width"
, "bottom"
, "box-shadow"
, "box-sizing"
, "break-after"
, "break-before"
, "break-inside"
, "caption-side"
, "clear"
, "clip"
, "color"
, "content"
, "cursor"
, "direction"
, "display"
, "empty-cells"
, "float"
, "font-family"
, "font-kerning"
, "font-size"
, "font-stretch"
, "font-style"
, "font-variant"
, "font-variant-ligatures"
, "font-variant-caps"
, "font-variant-numeric"
, "font-variant-east-asian"
, "font-weight"
, "height"
, "image-rendering"
, "isolation"
, "justify-items"
, "justify-self"
, "left"
, "letter-spacing"
, "line-height"
, "list-style-image"
, "list-style-position"
, "list-style-type"
, "margin-bottom"
, "margin-left"
, "margin-right"
, "margin-top"
, "max-height"
, "max-width"
, "min-height"
, "min-width"
, "mix-blend-mode"
, "object-fit"
, "object-position"
, "offset-distance"
, "offset-path"
, "offset-rotate"
, "opacity"
, "orphans"
, "outline-color"
, "outline-offset"
, "outline-style"
, "outline-width"
, "overflow-anchor"
, "overflow-wrap"
, "overflow-x"
, "overflow-y"
, "padding-bottom"
, "padding-left"
, "padding-right"
, "padding-top"
, "pointer-events"
, "position"
, "resize"
, "right"
, "scroll-behavior"
, "speak"
, "table-layout"
, "tab-size"
, "text-align"
, "text-align-last"
, "text-decoration"
, "text-decoration-line"
, "text-decoration-style"
, "text-decoration-color"
, "text-decoration-skip-ink"
, "text-underline-position"
, "text-indent"
, "text-rendering"
, "text-shadow"
, "text-size-adjust"
, "text-overflow"
, "text-transform"
, "top"
, "touch-action"
, "transition-delay"
, "transition-duration"
, "transition-property"
, "transition-timing-function"
, "unicode-bidi"
, "vertical-align"
, "visibility"
, "white-space"
, "widows"
, "width"
, "will-change"
, "word-break"
, "word-spacing"
, "z-index"
, "zoom"
, "-webkit-appearance"
, "backface-visibility"
, "-webkit-border-horizontal-spacing"
, "-webkit-border-image"
, "-webkit-border-vertical-spacing"
, "-webkit-box-align"
, "-webkit-box-decoration-break"
, "-webkit-box-direction"
, "-webkit-box-flex"
, "-webkit-box-ordinal-group"
, "-webkit-box-orient"
, "-webkit-box-pack"
, "-webkit-box-reflect"
, "column-count"
, "column-gap"
, "column-rule-color"
, "column-rule-style"
, "column-rule-width"
, "column-span"
, "column-width"
, "align-content"
, "align-items"
, "align-self"
, "flex-basis"
, "flex-grow"
, "flex-shrink"
, "flex-direction"
, "flex-wrap"
, "justify-content"
, "-webkit-font-smoothing"
, "grid-auto-columns"
, "grid-auto-flow"
, "grid-auto-rows"
, "grid-column-end"
, "grid-column-start"
, "grid-template-areas"
, "grid-template-columns"
, "grid-template-rows"
, "grid-row-end"
, "grid-row-start"
, "row-gap"
, "-webkit-highlight"
, "hyphens"
, "-webkit-hyphenate-character"
, "-webkit-line-break"
, "-webkit-line-clamp"
, "-webkit-locale"
, "-webkit-margin-before-collapse"
, "-webkit-margin-after-collapse"
, "-webkit-mask-box-image"
, "-webkit-mask-box-image-outset"
, "-webkit-mask-box-image-repeat"
, "-webkit-mask-box-image-slice"
, "-webkit-mask-box-image-source"
, "-webkit-mask-box-image-width"
, "-webkit-mask-clip"
, "-webkit-mask-composite"
, "-webkit-mask-image"
, "-webkit-mask-origin"
, "-webkit-mask-position"
, "-webkit-mask-repeat"
, "-webkit-mask-size"
, "order"
, "perspective"
, "perspective-origin"
, "-webkit-print-color-adjust"
, "-webkit-rtl-ordering"
, "shape-outside"
, "shape-image-threshold"
, "shape-margin"
, "-webkit-tap-highlight-color"
, "-webkit-text-combine"
, "-webkit-text-decorations-in-effect"
, "-webkit-text-emphasis-color"
, "-webkit-text-emphasis-position"
, "-webkit-text-emphasis-style"
, "-webkit-text-fill-color"
, "-webkit-text-orientation"
, "-webkit-text-security"
, "-webkit-text-stroke-color"
, "-webkit-text-stroke-width"
, "transform"
, "transform-origin"
, "transform-style"
, "-webkit-user-drag"
, "-webkit-user-modify"
, "user-select"
, "-webkit-writing-mode"
, "-webkit-app-region"
, "buffered-rendering"
, "clip-path"
, "clip-rule"
, "mask"
, "filter"
, "flood-color"
, "flood-opacity"
, "lighting-color"
, "stop-color"
, "stop-opacity"
, "color-interpolation"
, "color-interpolation-filters"
, "color-rendering"
, "fill"
, "fill-opacity"
, "fill-rule"
, "marker-end"
, "marker-mid"
, "marker-start"
, "mask-type"
, "shape-rendering"
, "stroke"
, "stroke-dasharray"
, "stroke-dashoffset"
, "stroke-linecap"
, "stroke-linejoin"
, "stroke-miterlimit"
, "stroke-opacity"
, "stroke-width"
, "alignment-baseline"
, "baseline-shift"
, "dominant-baseline"
, "text-anchor"
, "writing-mode"
, "vector-effect"
, "paint-order"
, "caret-color"
, "line-break" 
]



export default {
    compressHtml(str){
        // let styles = document.querySelectorAll('style');

        // let str = `<div class="header-title" style="font-size:150px">你是谁</div>`
        // let divText = document.createElement('div')
        // divText.innerHTML = str

        // let style =`<style type="type/css">.header-title{font-size:1000px;}</style>`
        // let styleText = document.createElement('div')
        // styleText.innerHTML = style;


        // let str1= new XMLSerializer().serializeToString(divText); 

        //  let htmlSvg = 'data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" width="300" height="200">'+
        //  '<foreignObject x="0" y="0" width="100%" height="100%">'
        //        +str1+styleText.innerHTML+'</foreignObject></svg>';
            
        //     console.log(htmlSvg);
        //     //  htmlSvg = htmlSvg.replace(/\n/g, '').replace(/\t/g, '').replace(/#/g, '%23');
            
        //     // let xmls = new XMLSerializer().serializeToString(this.$el)
        
       
        // this.imageUrl = htmlSvg   
    },
    getStyle() {
        
        let styles = document.querySelectorAll('style');
        let str = "";
        styles.forEach(item=>{
            str+=item.outerHTML;
        })

             
        return styles 
    },
    getSvg(node) {
        let content = window.getComputedStyle(node);

        
        
    },
    getSvg(htmlText) {
        // let divText = document.createElement('div')
        // divText.innerHTML = htmlText;
        // let str= new XMLSerializer().serializeToString(devText.firstChild);

        // let htmlSvg = 'data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" width="300" height="200">'+
        //  '<foreignObject x="0" y="0" width="100%" height="100%">'
        //        +str+'</foreignObject></svg>';

        //        return htmlSvg
            
    }
    
}
